# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'colordetectparam.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QSlider, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1070, 0, 362, 851))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.mainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)

        self.mainLayout.setObjectName("mainLayout")
        self.layout_alpha_beta = QtWidgets.QVBoxLayout()
        self.layout_alpha_beta.setObjectName("layout_alpha_beta")
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_26.setToolTipDuration(-1)
        self.label_26.setObjectName("label_26")
        self.layout_alpha_beta.addWidget(self.label_26, 0, QtCore.Qt.AlignHCenter)
        
        #sliderlayout_1
        self.sliderlayout_1 = QtWidgets.QVBoxLayout()
        self.sliderlayout_1.setObjectName("sliderlayout_1")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(300, 20))
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setScaledContents(True)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.sliderlayout_1.addWidget(self.label_17)
        self.sub_sliderlayout_1 = QtWidgets.QHBoxLayout()
        self.sub_sliderlayout_1.setObjectName("sub_sliderlayout_1")
        self.slider_alpha_left = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.slider_alpha_left.setOrientation(QtCore.Qt.Horizontal)
        self.slider_alpha_left.setRange(0, 100)
        self.slider_alpha_left.setTickPosition(QSlider.TicksBothSides)
        self.slider_alpha_left.valueChanged.connect(self.changedValue)
        self.slider_alpha_left.setObjectName("slider_alpha_left")
        self.sub_sliderlayout_1.addWidget(self.slider_alpha_left)
        self.label_alpha_left = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_alpha_left.setFrameShape(QtWidgets.QFrame.Box)
        self.label_alpha_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_alpha_left.setObjectName("label_alpha_left")
        self.sub_sliderlayout_1.addWidget(self.label_alpha_left)
        self.sliderlayout_1.addLayout(self.sub_sliderlayout_1)
        self.layout_alpha_beta.addLayout(self.sliderlayout_1)

        #sliderlayout_2
        self.sliderlayout_2 = QtWidgets.QVBoxLayout()
        self.sliderlayout_2.setObjectName("sliderlayout_2")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(300, 20))
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.sliderlayout_2.addWidget(self.label_15)
        self.sub_sliderlayout_2 = QtWidgets.QHBoxLayout()
        self.sub_sliderlayout_2.setObjectName("sub_sliderlayout_2")
        self.slider_beta_left = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.slider_beta_left.setOrientation(QtCore.Qt.Horizontal)
        self.slider_beta_left.valueChanged.connect(self.changedValue)
        self.slider_beta_left.setTickPosition(QSlider.TicksBothSides)
        self.slider_beta_left.setRange(0, 100)
        self.slider_beta_left.setObjectName("slider_beta_left")
        self.sub_sliderlayout_2.addWidget(self.slider_beta_left)
        self.label_beta_left = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_beta_left.setFrameShape(QtWidgets.QFrame.Box)
        self.label_beta_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_beta_left.setObjectName("label_beta_left")
        self.sub_sliderlayout_2.addWidget(self.label_beta_left)
        self.sliderlayout_2.addLayout(self.sub_sliderlayout_2)
        self.layout_alpha_beta.addLayout(self.sliderlayout_2)

        #sliderlayout_3
        self.sliderlayout_3 = QtWidgets.QVBoxLayout()
        self.sliderlayout_3.setObjectName("sliderlayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(300, 20))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.sliderlayout_3.addWidget(self.label_5)
        self.sub_sliderlayout_3 = QtWidgets.QHBoxLayout()
        self.sub_sliderlayout_3.setObjectName("sub_sliderlayout_3")
        self.slider_alpha_right = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.slider_alpha_right.setOrientation(QtCore.Qt.Horizontal)
        self.slider_alpha_right.setRange(0, 100)
        self.slider_alpha_right.setTickPosition(QSlider.TicksBothSides)
        self.slider_alpha_right.valueChanged.connect(self.changedValue)
        self.slider_alpha_right.setObjectName("slider_alpha_right")
        self.sub_sliderlayout_3.addWidget(self.slider_alpha_right)
        self.label_alpha_right = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_alpha_right.setFrameShape(QtWidgets.QFrame.Box)
        self.label_alpha_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_alpha_right.setObjectName("label_alpha_right")
        self.sub_sliderlayout_3.addWidget(self.label_alpha_right)
        self.sliderlayout_3.addLayout(self.sub_sliderlayout_3)
        self.layout_alpha_beta.addLayout(self.sliderlayout_3)

        #sliderlayout_4
        self.sliderlayout_4 = QtWidgets.QVBoxLayout()
        self.sliderlayout_4.setObjectName("sliderlayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(300, 20))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.sliderlayout_4.addWidget(self.label_4, 0, QtCore.Qt.AlignVCenter)
        self.sub_sliderlayout_4 = QtWidgets.QHBoxLayout()
        self.sub_sliderlayout_4.setObjectName("sub_sliderlayout_4")
        self.slider_beta_right = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.slider_beta_right.setOrientation(QtCore.Qt.Horizontal)
        self.slider_beta_right.setRange(0,100)
        self.slider_beta_right.setTickPosition(QSlider.TicksBothSides)
        self.slider_beta_right.valueChanged.connect(self.changedValue)
        self.slider_beta_right.setObjectName("slider_beta_right")
        self.sub_sliderlayout_4.addWidget(self.slider_beta_right)
        self.label_beta_right = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_beta_right.setFrameShape(QtWidgets.QFrame.Box)
        self.label_beta_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_beta_right.setObjectName("label_beta_right")
        self.sub_sliderlayout_4.addWidget(self.label_beta_right)
        self.sliderlayout_4.addLayout(self.sub_sliderlayout_4)
        self.layout_alpha_beta.addLayout(self.sliderlayout_4)
        #
        self.mainLayout.addLayout(self.layout_alpha_beta)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.mainLayout.addWidget(self.line)
        # Done layout alpha beta
        
        

        self.layout_threshold = QtWidgets.QVBoxLayout()
        self.layout_threshold.setContentsMargins(-1, 0, 0, 0)
        self.layout_threshold.setObjectName("layout_threshold")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.layout_threshold.addWidget(self.label_25, 0, QtCore.Qt.AlignHCenter)
        self.threshlayout_1 = QtWidgets.QVBoxLayout()
        #threshlayout_1
        self.threshlayout_1.setObjectName("threshlayout_1")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(300, 64))
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setObjectName("label_22")
        self.threshlayout_1.addWidget(self.label_22)
        self.sub_threshlayout_1 = QtWidgets.QHBoxLayout()
        self.sub_threshlayout_1.setObjectName("sub_threshlayout_1")
        self.slider_supp_threshold = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.slider_supp_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.slider_supp_threshold.setRange(1, 100)
        self.slider_supp_threshold.setTickPosition(QSlider.TicksBothSides)
        self.slider_supp_threshold.valueChanged.connect(self.changedValue)
        self.slider_supp_threshold.setObjectName("slider_supp_threshold")
        self.sub_threshlayout_1.addWidget(self.slider_supp_threshold)
        self.label_supp_threshold = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_supp_threshold.setFrameShape(QtWidgets.QFrame.Box)
        self.label_supp_threshold.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_supp_threshold.setObjectName("label_supp_threshold")
        self.sub_threshlayout_1.addWidget(self.label_supp_threshold)
        self.threshlayout_1.addLayout(self.sub_threshlayout_1)
        self.layout_threshold.addLayout(self.threshlayout_1)
        #threshlayout_3
        self.threshlayout_3 = QtWidgets.QHBoxLayout()
        self.threshlayout_3.setObjectName("threshlayout_3")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_24.setToolTipDuration(-1)
        self.label_24.setObjectName("label_24")
        self.threshlayout_3.addWidget(self.label_24)
        self.layout_threshold.addLayout(self.threshlayout_3)
        #threshlayout_3
        self.threshlayout_4 = QtWidgets.QHBoxLayout()
        self.threshlayout_4.setObjectName("threshlayout_4")
        self.spinBox_7 = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_7.setMaximum(8192)
        self.spinBox_7.setObjectName("spinBox_7")
        self.threshlayout_4.addWidget(self.spinBox_7)
        self.spinBox_8 = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_8.setMaximum(8192)
        self.spinBox_8.setObjectName("spinBox_8")
        self.threshlayout_4.addWidget(self.spinBox_8)
        self.spinBox_9 = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_9.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_9.setMaximum(8192)
        self.spinBox_9.setObjectName("spinBox_9")
        self.threshlayout_4.addWidget(self.spinBox_9)
        self.layout_threshold.addLayout(self.threshlayout_4)
        #threshlayout_5
        self.threshlayout_5 = QtWidgets.QHBoxLayout()
        self.threshlayout_5.setObjectName("threshlayout_5")
        self.btnSaveConfig = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnSaveConfig.setObjectName("btnSaveConfig")
        self.threshlayout_5.addWidget(self.btnSaveConfig)
        self.layout_threshold.addLayout(self.threshlayout_5)
        self.threshlayout_6 = QtWidgets.QHBoxLayout()
        self.threshlayout_6.setObjectName("threshlayout_6")
        self.btnBack = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnBack.setObjectName("btnBack")
        self.threshlayout_6.addWidget(self.btnBack)
        self.layout_threshold.addLayout(self.threshlayout_6)
        self.mainLayout.addLayout(self.layout_threshold)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_26.setText(_translate("MainWindow", "ALPHA - BETA CONFIGURATION"))
        self.label_17.setText(_translate("MainWindow", "Alpha Left(Contrast): "))
        self.label_alpha_left.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "Beta Left(Brightness): "))
        self.label_beta_left.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Alpha Right (Contrast):"))
        self.label_alpha_right.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Beta Right (Brightness):"))
        self.label_beta_right.setText(_translate("MainWindow", "0"))
        self.label_25.setText(_translate("MainWindow", "THRESHOLD CONFIGURATION"))
        self.label_22.setText(_translate("MainWindow", "Supp Threshold: "))
        self.label_supp_threshold.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "Amplify Threshold: "))
        self.btnSaveConfig.setText(_translate("MainWindow", "Save Config"))
        self.btnBack.setText(_translate("MainWindow", "Go Back"))

    def changedValue(self, value):
        if MainWindow.sender() == self.slider_alpha_left:
            size = self.slider_alpha_left.value()
            self.label_alpha_left.setText(str(size))
        elif MainWindow.sender() == self.slider_alpha_right:
            size = self.slider_alpha_right.value()
            self.label_alpha_right.setText(str(size))
        elif MainWindow.sender() == self.slider_beta_right:
            size = self.slider_beta_right.value()
            self.label_beta_right.setText(str(value))
        elif MainWindow.sender() == self.slider_beta_left:
            size = self.slider_beta_left.value()
            self.label_beta_left.setText(str(value))
        elif MainWindow.sender() == self.slider_supp_threshold:
            size = self.slider_supp_threshold.value()
            self.label_supp_threshold.setText(str(value))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec_())